### ISSUE TITLE
Auslesen der Description bei Views

### ISSUE THREAD

**Issue by xStaer** [patschwork/meta_grid#1]
Ist es möglich bei Views aus dem SQL Server die Description aus dem Code mit auszulesen?

**Comment by patschwork** [comment]
Aktuell ist das noch nicht möglich, allerdings ist diese Funktion bereits für Stored Procedures umgesetzt. Dieses Prinzip kann genutzt wiederverwendet werden.
Feature wird in das nächste Release aufgenommen.

**Comment by patschwork** [comment]
Dem Release 2.4.1 zugeordnet.

**Comment by patschwork** [comment]
Feature wurde implementiert.
