### ISSUE TITLE
Passwort Reset funktioniert nicht

### ISSUE THREAD

**Issue by xStaer** [patschwork/meta_grid#5]
weder über Reset noch als admin in der User Verwaltung

**Comment by patschwork** [comment]
Hallo @xStaer,

dies hat zwei Ursachen.

## Passwort Reset
Hierzu muss der Mailserver (smtp) korrekt konfiguriert werden. Wenn die Konfiguration inkorrekt ist läuft der Mailversand in einen Timeout. 
Korrekt ist, dass nach der Eingabe der E-Mail dem Betätigen des Buttons "Continue" eine Hinweismeldung in einem blauen Rahmen als Bestätigung erscheint wenn die Mail erstellt+versendet wurde.

### Mailserverkonfiguration
Die Konfiguration muss im config-file erfolgen `meta_grid/config/web.php`.

Nachfolgend ein Beispiel für die Konfiguration

```php
        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            // send all mails to a file by default. You have to set
            // 'useFileTransport' to false and configure a transport
            // for the mailer to send real emails.
            'useFileTransport' => false,
            'transport' => [
                'class' => 'Swift_SmtpTransport',
                'encryption' => 'ssl',
                'host' => 'smtp.xyz.com',
                'port' => '465',
                'username' => 'MAIL_USER_ACCOUNT',
                'password' => 'MAIL_USER_PASSWORD',
            ],             
        ],
```
Dabei ist die Angabe des `port` und der `encryption` (gültige Werte sind `ssl` und `tls`) wichtig! 
Die meisten Mailserver verlangen heutzutage `ssl`.

Zudem ist es sinnvoll die Absende-Mail-Adresse für den Passwortreset (gilt auch für User-Registrierungen) anzugeben. 
Dies erfolgt auch in der Datei `meta_grid/config/web.php` (und `meta_grid/config/params.php`)

In der Datei `meta_grid/config/web.php` folgendes (unten) ergänzen sofern nicht vorhanden:

```php
        'user' => [
                    'class' => Da\User\Module::class,
                    'classMap' => [
                        'User' => 'vendor\meta_grid\user_model\User',
                    ],
                    'administrators' => ['admin'],
                    'administratorPermissionName' => 'mgadmin',
                    'mailParams' => [
                        'fromEmail' => $params['adminEmail'],
                    ],
                ],
```

Hierbei gilt, dass die Angabe ```'fromEmail' => $params['adminEmail']``` aus dem Wert in der Datei `meta_grid/config/params.php` gezogen wird.

In der Datei `meta_grid/config/params.php` wird die Mail-Adresse definiert:
```php
<?php

return [
    'adminEmail' => 'NOREPLY_META_GRID_ADMIN@MYDOMAIN.TLD',
];
```

## Ändern des Passworts in der Useradministration
Hier gibt es einen Bug in der User-Komponente. Dieses ist im nächsten Release als Workaround gefixt.
Ein manueller Eingriff ist aber schnell gemacht, damit es wieder ordnungsgemäß funktioniert...
In der Datei `meta_grid/vendor/meta_grid/user_model/User.php` folgende function ergänzen:

```php
	public function rules()
	{
		$rules = parent::rules();
		unset($rules['twoFactorEnabledNumber']);
		return $rules; 
	}
```
(Auf die letzte } der Klasse achten... ;-) )

Nach dem Betätigen des Button "Update" in der Useradministration erscheint hier ebenfalls eine Hinweismeldung in einem grünen Rahmen mit dem Text "Account details have been updated".

**Comment by patschwork** [comment]
Dem Release 2.4.1 zugeordnet.

**Comment by patschwork** [comment]
Bugfix wurde implementiert.
