### ISSUE TITLE
Neues FEATURE: Export von Inhalten als Liste

### ISSUE THREAD

**Issue by xStaer** [patschwork/meta_grid#6]
Für notwendige Dokumentationen in Listenform wird eine Exportfunktion benötigt. 
Idealerweise könnten über eine Auswahlmaske Attribute ausgewählt werden, welche dann als CSV oder txt exportiert werden kann.

Im ersten Schritt würden definierte Exports ausreichen. Dabei könnte eine definierte Attributliste als CSV oder TXT exportierbar sein.
Notwendige Export sind:

**Feldliste**
- Feldname
- Feldbeschreibung
- Tabelle
- Datenbank
- Feldattribute (DSGVO, PK, FK)
- Mappings ???

Eventuell ist es im Vorfeld möglich die Feldattribute zu filtern.

**Tabelleliste**
- Tabellenname
- alle Felder (inklusive Attributen) siehe Feldlisteexport
- Datenbank
- Mappings ???

Eventuell ist es im Vorfeld möglich die Mappings zu filtern. Hintergrund ist ein zugeordnetes Attribut z.B. DSGVO mit welchem eine ganze Tabelle als DSGVO Relevant gekennzeichnet ist.

**Comment by patschwork** [comment]
Dem Release 2.4.1 zugeordnet.

**Comment by patschwork** [comment]
Feature wurde implementiert.
