### ISSUE TITLE
Neues FEATURE: Direction der Mappings auswählbar

### ISSUE THREAD

**Issue by xStaer** [patschwork/meta_grid#7]
Bei der Zuordnung von Mappings gibt es die Richtungspfeile. Leider sind diese durch das System vorgeben, was bei automatischen Zuordnungen noch funktioniert, ist bei manuellen Zuweisungen teilweise nicht korrekt.

Dies sollte anpassbar oder beim Mapping auswählbar sein

**Comment by patschwork** [comment]
Dem Release 2.4.1 zugeordnet.

In der Mappingliste kann die Richtung angepasst werden (sofern auch der Benutzer das Recht hat, Mappings zu erstellen)

![image](https://user-images.githubusercontent.com/10715292/91898232-b8a30980-ec9b-11ea-9016-4928998a02a5.png)

**Comment by patschwork** [comment]
Feature wurde implementiert.
